### ISSUE TITLE
Grant access to initial maintainers

### ISSUE THREAD

**Issue by tnewbau** [mycloudnexus/cc-api-sandbox#1]
promote initial maintainers to be able initial branch and start adding work towards the cc-api-sandbox.

**Comment by LawrenceLim** [comment]
I have added you to the team. if you could share the remaining github handle, i can add them as well.

**Comment by tnewbau** [comment]
Thanks Lawerence! Please invite the following members of the team initially:
Tiana Newbauer-Hampton: tnewbau
John-Michael (JMO) O'Brien: JimTheCactus
Trent Gamber: tgamber-stateless
Sarah Wheeler: swheeler-stateless
Michael (Mikey) Brown: michaelbrown-stateless
