### ISSUE TITLE
CI Failing Due to Missing Secret

### ISSUE THREAD

**Issue by JimTheCactus** [mycloudnexus/cc-api-sandbox#19]
Heya folks! I was looking at trying to get my PRs reviewed and merged and I noticed that something is up with the CI. Seems like there may be a secret that isn't set presently. I don't have vision into that part of the system, so I figured I'd let you know.

You can see this in my run at https://github.com/mycloudnexus/cc-api-sandbox/actions/runs/11297047899/job/31520048914

![image](https://github.com/user-attachments/assets/9019ea49-f713-4445-9bfe-188c2f7c1b2a)

**Comment by RyanDinglei** [comment]
According the github docs: https://docs.github.com/en/actions/security-for-github-actions/security-guides/using-secrets-in-github-actions#using-secrets-in-a-workflow
`With the exception of GITHUB_TOKEN, secrets are not passed to the runner when a workflow is triggered from a forked repository.`

**Comment by RyanDinglei** [comment]
we may use the pull_request_target events  instead of pull_request for CI workflow. https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/approving-workflow-runs-from-public-forks
make a pr for that: https://github.com/mycloudnexus/cc-api-sandbox/pull/20

**Comment by JimTheCactus** [comment]
Mixing `pull_request_target` and the [explicit checkout)(https://github.com/mycloudnexus/cc-api-sandbox/blob/b96012f0fd068bfe59ede5d88993c11266d9dde0/.github/workflows/nodejs-yarn-unit-tests.yaml#L20) presents a security hazard, and we'll want to search for a different solution.

You can read more about the challenge this poses at the GitHub article https://securitylab.github.com/resources/github-actions-preventing-pwn-requests/

**Comment by RyanDinglei** [comment]
Hi folks. 
Due to the security risk, could we according the user permission to trigger the workflow which has been reviewed.
refer the article: https://michaelheap.com/access-secrets-from-forks/
The process should be:
- Pr from fork repo, the workflow will check the user permission. if not match, the workflow will failed.
- After the repo's maintainer reviewed the pr, and re-run the workflow. then will match the user permission check. workflow can get the secrets.
Also have to decide the user who can review the pr and appropriate permission for the repo.

**Comment by RyanDinglei** [comment]
and deleted the sonar-project.properties file according the docs https://docs.sonarsource.com/sonarcloud/advanced-setup/automatic-analysis/#activating-automatic-analysis:
`SonarCloud will reject a project for automatic analysis if it contains a sonar-project.properties file `

**Comment by DaveXiong** [comment]
@RyanDinglei  when `auomatic analysis` enabled , is it still possible to generate the code coverage report ?

**Comment by JimTheCactus** [comment]
Heya folks! Was trying to work through getting the PRs merged, and noticed that there's a call to write to the comments from inside the workflow. Unsurprisingly, this fails since we don't have tokens in this context.

![image](https://github.com/user-attachments/assets/174bf869-11db-453b-9e87-f1d65003b59c)

Effectively this is the same issue as the sonar checks and will require a similarly nuanced solution. Simply injecting the token won't work for the same reasons; there's foreign, untrusted code in the PR. There may be a way to do something similar with a job artifact and a second job, but the artifact would have to be regarded as untrusted.

I would suggest that it's sufficient to require that the action's console output be reviewed to know what went wrong, but please don't construe that as a requirement of the solution.

**Comment by RyanDinglei** [comment]
Hi @JimTheCactus According the docs: https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#permissions-for-the-github_token, the GITHUB_TOKEN permissions for pull requests from public forked repositories are all "read". So the failed step need to "pull_request: write" permission to add comment to the pr.

**Comment by RyanDinglei** [comment]
For the issue, I've updated the workflow to add conditions for forked repo. https://github.com/mycloudnexus/cc-api-sandbox/blob/main/.github/workflows/nodejs-yarn-unit-tests.yaml#L70 and https://github.com/mycloudnexus/cc-api-sandbox/blob/main/.github/workflows/nodejs-yarn-unit-tests.yaml#L91. for the PRs not came from forked repo, the add comments to PR is working fine. for the PRS came from forker repo, will not do the add comment stuff. Can find the vulnerability in the workflow log if find the step failed. And i made a [PR](https://github.com/mycloudnexus/cc-api-sandbox/pull/28) from forked repo.  and also made a [PR ](https://github.com/mycloudnexus/cc-api-sandbox/pull/27) from the repo for testing. looks good for now.

**Comment by RyanDinglei** [comment]
> @RyanDinglei when `auomatic analysis` enabled , is it still possible to generate the code coverage report ?

yes, can check the 2 PRs as i mentioned above.

**Comment by JimTheCactus** [comment]
Looking at it, it seems to work and is sane, so long as you limit committing directly to the repo only to *absolutely trusted* users (which is pretty typical.)

Thanks a ton for looking in to this!
